augment_multiplier: 1
batch_size: 128
beta1: 0.5
beta2: 0.999
checkpoint_path: checkpoints/best_AbleKrystle.pt
d_lr: 0.0001
data_dir: ./data
epochs: 1
feature_maps: 64
fixed_samples_size: 16
g_lr: 0.0004
grad_clip: 1.0
latent_dim: 100
log_dir: runs
n_critic: 2
num_eval_samples: 1000
num_workers: 4
patience: 25
project_name: gan-cifar10
save_dir: checkpoints
subset_size: 150
