batch_size: 128
checkpoint_path: checkpoints/MonthlyJillian_best.pt
data_dir: ./data
device: cuda
epochs: 1
initial_lr: 0.0001
kl_weight: 0.1
num_vis_samples: 10
num_workers: 4
project_name: vae-cifar
subset_size: 200
